"use client";
import { createBrowserClient } from "@supabase/ssr";
import type { Database } from "@/types/database";

// ⚠️ DO NOT EDIT THIS FILE.

const TOOL_SCHEMA = process.env.NEXT_PUBLIC_TOOL_SCHEMA!;

export function createClient() {
  return createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { db: { schema: TOOL_SCHEMA as never } }
  );
}
