import { createServerClient, type CookieOptions } from "@supabase/ssr";
type CookieToSet = { name: string; value: string; options?: CookieOptions };
import { NextResponse, type NextRequest } from "next/server";

// ⚠️ DO NOT EDIT THIS FILE. If login seems broken, message the lead.

const COOKIE_DOMAIN =
  process.env.NODE_ENV === "production"
    ? process.env.NEXT_PUBLIC_COOKIE_DOMAIN
    : undefined;

export async function updateSession(request: NextRequest) {
  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll: () => request.cookies.getAll(),
        setAll: (cookiesToSet: CookieToSet[]) => {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value)
          );
          response = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, {
              ...options,
              domain: COOKIE_DOMAIN,
            })
          );
        },
      },
    }
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const isDevLogin = request.nextUrl.pathname.startsWith("/dev-login");

  if (!user && !isDevLogin) {
    if (
      process.env.NODE_ENV === "development" ||
      !process.env.NEXT_PUBLIC_PORTAL_LOGIN_URL
    ) {
      return NextResponse.redirect(new URL("/dev-login", request.url));
    }
    const login = new URL(process.env.NEXT_PUBLIC_PORTAL_LOGIN_URL);
    login.searchParams.set("next", request.url);
    return NextResponse.redirect(login);
  }

  return response;
}
